# Generated by Django 5.2.3 on 2025-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='digital_store.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_types',
            field=models.ManyToManyField(to='digital_store.producttype', verbose_name='Типы товара'),
        ),
    ]
